// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rupzsdzdkyanikywdxkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cHpzZHpka3lhbmlreXdkeGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzkzMzksImV4cCI6MjA2NTAxNTMzOX0.IBxY5bZUFajV_3EtEvpNPbv_7bVlzPL757ihy0dbcGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);